#-------------------------------
# Author Settings
author:
  name: Do-young
  image: 01.jpg

#-------------------------------
# General Site Settings
title: Logs
logo: logo.png # You can add own logo.
description: dodo's programming log


#-------------------------------
# Contact links
linkedin: https://www.linkedin.com/in/%EB%8F%84%EC%98%81-%ED%99%A9-374206144/
github: https://github.com/dodo4513

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
